# Generated by Django 3.2.12 on 2022-03-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('currentBalance', models.CharField(max_length=100, verbose_name='Текущий баланс')),
                ('addDate', models.DateField(verbose_name='Дата добавления')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('city', models.CharField(max_length=100, verbose_name='Город проживания')),
                ('lastActivity', models.DateField(verbose_name='Временная метка последней активности')),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('startDate', models.DateField(verbose_name='Дата начала действия')),
                ('endDate', models.DateField(verbose_name='Дата конца действия')),
                ('minutesCount', models.IntegerField(verbose_name='Объем минут')),
                ('smsCount', models.IntegerField(verbose_name='Объем смс')),
                ('traficCount', models.IntegerField(verbose_name='Объем трафика (мб)')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Метка времени')),
                ('operationType', models.CharField(choices=[(1, 'Звонок'), (2, 'смс'), (3, 'Трафик')], max_length=16, verbose_name='Тип услуги(звонок, смс, трафик)')),
                ('spentValue', models.IntegerField(verbose_name='Объем затраченных единиц')),
                ('abonent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiProj.abonent', verbose_name='id абонента')),
            ],
        ),
        migrations.AddField(
            model_name='abonent',
            name='activeTarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiProj.tarif', verbose_name='Активный тариф'),
        ),
    ]
